import { CONFIG_PORTS } from "."

const {
    PORT, 
    DB_PORT, 
    SMTP_PORT, 
    ACTIVATION_TOKEN_EXPIRE,
    ACCESS_TOKEN_EXPIRE, 
    REFRESH_TOKEN_EXPIRE
}  = CONFIG_PORTS;

export {
    PORT, 
    DB_PORT, 
    SMTP_PORT, 
    ACTIVATION_TOKEN_EXPIRE,
    ACCESS_TOKEN_EXPIRE, 
    REFRESH_TOKEN_EXPIRE
}