export const SUCCESS = true;
export const MINUTE_TO_MILLISECONDS = 60*1000;
export const ONE_DAY_TO_MILLISECONDS = 24 * 60 * MINUTE_TO_MILLISECONDS;
export const ONE_MONTH_TO_MILLISECONDS = 30 * ONE_DAY_TO_MILLISECONDS;
export const SEVEN_DAYS_TO_SECONDS = 7 * 24 * 60 * 60;
export const CRON_MID_NIGHT_TIME_STAMP = "0 0 0 * * *";